name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      
    - name: Get cmake
      uses: lukka/get-cmake@latest
  
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
      
    - name: Build
      run: cmake --build build --parallel
      
    - name: Test
      run: ./pbrt_test
      working-directory: build
